# wbc-app.yaml
apiVersion: v1
kind: Service
metadata:
  name: wbc-app-service
spec:
  selector:
    app.kubernetes.io/name: wbc-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wbc-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: wbc-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wbc-app
    spec:
      containers:
      - name: wbc-app-container
        image: linkpond0629/wbc:a9ca1c742c88527baa707c31e78c04813e33b76d
        ports:
          - protocol: TCP
            containerPort: 8080